config/routes.rb
Rails.application.routes.draw do
  get 'post/new', to: "post#new", as: :new_posts
  post 'post/new', to: "post#create", as: :posts
  get 'posts/', to: "post#index", as: :all_post
  get 'post/:id', to: "post#show", as: :detail_post

  devise_for :users, skip: [:passwords]
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  has_many :posts

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :page_required_auth

  # method for handle authentication required when visit a site
  def page_required_auth
    unless user_signed_in?
      redirect_back fallback_location: root_path
    end
  end

  protected
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :page_required_auth

  def new
    @post = Post.new
  end

  def index
    # sort list post by updated time
    @list_post = Post.all.order(updated_at: :desc)
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = Post.new(create_post_param)
    @post.user = current_user
    if @post.save
      redirect_to '/'
    else
      flash[:error] = "Cant't save post, some error occurred"
    end
  end

  private
  def create_post_param
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    options = %i[hard_wrap autolink no_intra_emphasis fenced_code_blocks]
    Markdown.new(text, **options).to_html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/home/index.html.erb
<% content_for :title, "Liblog: Keep sharing, more growing" %>
<% if user_signed_in? %>
  <h1 class="text-3xl font-bold">Welcome back, <span class="text-gradient from-sky-400 to-blue-600"><%= current_user.username %></span>!</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://ajaxorg.github.io/ace-builds/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
  </head>

  <body>
    <nav class="bg-gray-100">
      <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-16 items-center justify-between">
          <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            <!-- Mobile menu button-->
            <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
              <span class="absolute -inset-0.5"></span>
              <span class="sr-only">Open main menu</span>
              <!--
                Icon when menu is closed.

                Menu open: "hidden", Menu closed: "block"
              -->
              <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
              <!--
                Icon when menu is open.

                Menu open: "block", Menu closed: "hidden"
              -->
              <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
            <div class="flex flex-shrink-0 items-center">
              <%= link_to "LIBLOG", root_path, class: 'text-gradient from-sky-400 to-blue-600 text-2xl font-medium tracking-wide', title: 'liblog: keep sharing, more growing' %>
            </div>
            <div class="hidden sm:ml-6 sm:block">
              <div class="flex space-x-4">
                <%= link_to "Posts", all_post_path, class: 'text-black bg-gray-100 hover:bg-gray-200 rounded-xl px-3 py-2 text-sm font-medium' %>
                <%= link_to "Team", "#", class: 'text-black bg-gray-100 hover:bg-gray-200 rounded-xl px-3 py-2 text-sm font-medium' %>
                <%= link_to "Project", "#", class: 'text-black bg-gray-100 hover:bg-gray-200 rounded-xl px-3 py-2 text-sm font-medium' %>
                <%= link_to "About", "#", class: 'text-black bg-gray-100 hover:bg-gray-200 rounded-xl px-3 py-2 text-sm font-medium' %>
              </div>
            </div>
          </div>
          <% if user_signed_in? %>
            <%= render 'shared/user_dropdown', user: current_user %>
          <% else %>
            <div class="space-x-2 absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                <%= button_to "Sign in", new_user_session_path, method: :get, class: 'btn-primary text-sm' %>
                <%= button_to "Sign up", new_user_registration_path, method: :get, class: 'btn-second text-sm'%>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

    <main class="container mx-auto mt-28 mb-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/post/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Post#create</h1>
  <p>Find me in app/views/post/create.html.erb</p>
</div>

app/views/post/index.html.erb
<% content_for :title, "Newest posts - Liblog" %>

<div class="w-8/12">
  <div class="flex justify-between items-center">
    <h1 class="text-4xl font-bold tracking-tight text-gradient from-sky-400 to-blue-600">Newest Posts</h1>
    <%= button_to "New post", new_posts_path, method: :get, class: 'btn-primary text-sm' %>
  </div>
  <div class="space-y-2 mt-4">
  <% @list_post.each do |post| %>
    <div class="flex items-center border w-full shadow-md space-y-1 py-3 rounded-xl">
      <div class="flex justify-center items-center w-20">
        <% if post.vote == 0 %>
          <p class="text-xl font-bold text-center text-gray-300" title="Voting">=<%= post.vote %></p>
        <% elsif post.vote > 0 %>
          <p class="text-xl font-bold text-center text-green-400" title="Voting">+<%= post.vote %></p>
        <% else %>
          <p class="text-xl font-bold text-center text-red-500" title="Voting"><%= post.vote %></p>
        <% end %>
      </div>
      <div class="flex-row">
        <div class="flex">
          <span class="text-sm">
            <span class="hover:underline hover:text-blue-600 cursor-pointer"><%= post.user.username %></span>
            -
            <%= post.created_at %>
          </span>
        </div>
        <div class="flex">
          <%= link_to post.title, detail_post_path(post.id), class: 'text-sm text-black font-medium' %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/post/new.html.erb
<div class="w-full">
  <%= form_for @post do |p| %>
    <div>
      <%= p.label "Title: " %><br/>
      <%= p.text_field :title, class: 'ui-input w-full', placeholder: 'Enter your title' %><br/>
      <em class="text-sm"><span class="text-red-500">*</span>(title will be heading 1 on your post)</em>
    </div>
    <div class="mt-5">
      Content
      <em>
        (write by <%= link_to :markdown, "https://www.markdownguide.org/", target: :_blank, class: 'text-blue-600 underline' %> language)
        <span class="text-red-500">*</span>
      </em>
      :
    </div>
    <div id="editor-area" class="mt-2">
      <div id="editor-menu-strip" class="flex justify-end bg-gray-100 items-center rounded-t-xl py-1.5 px-4 text-sm space-x-1">
        <div id="heading-menu-strip">
          <button onclick="insertHeading(1)" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg" type="button" title="Insert heading 1">H1</button>
          <button onclick="insertHeading(2)" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg" type="button" title="Insert heading 2">H2</button>
          <button onclick="insertHeading(3)" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg" type="button" title="Insert heading 3">H3</button>
          <button onclick="insertHeading(4)" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg" type="button" title="Insert heading 4">H4</button>
          <button onclick="insertHeading(5)" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg" type="button" title="Insert heading 5">H5</button>
          <button onclick="insertHeadin(6)" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg" type="button" title="Insert heading 6">H6</button>
        </div>
        <div id="text-menu-strip">
          <button onclick="insertBoldText()" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg font-bold" type="button" title="Bold text">Bold</button>
          <button onclick="insertItalicText()" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg italic" type="button" title="Bold text">Italic</button>
          <button onclick="insertUnderlineText()" class="border border-gray-300 px-1.5 py-1 text-xs rounded-lg underline" type="button" title="Bold text">Underline</button>
        </div>
      </div>
      <div id="editor" class="rounded-b-xl border w-max">
        <%= p.text_area :content %><br/>
      </div>
    </div>
    <div class="mt-3 flex justify-end">
    <%= p.submit "Create post", class: 'btn-primary text-sm' %>
    </div>
  <% end %>
</div>
<script>
  var editor = ace.edit("editor");
  var session = editor.getSession();
  session.setUseWorker(false);
  //editor.setTheme('ace/theme/eclipse');
  session.setMode('ace/mode/markdown');
  editor.setValue("");

  /* for key binding of editor */
  editor.commands.addCommand({
      name: "insertBoldText",
      bindKey: { win: "Ctrl-b", mac: "Control-b" },
      exec: function(editor) { insertBoldText(); }
  });
  editor.commands.addCommand({
      name: "insertItalicText",
      bindKey: { win: "Ctrl-i", mac: "Control-i" },
      exec: function(editor) { insertItalicText(); }
  });
  editor.commands.addCommand({
      name: "insertItalicText",
      bindKey: { win: "Ctrl-u", mac: "Control-u" },
      exec: function(editor) { insertUnderlineText(); }
  });

  function insertHeading( heading ) {
      var current_position = editor.getCursorPosition();
      session.insert(current_position, '\n' + '#'.repeat(heading) + ' ');
  }

  function insertBoldText() {
      var current_position = editor.getCursorPosition();
      console.log(current_position);
      session.insert(current_position, '**** ');

      // for moving cursor at center of bold mark
      var next_pos = editor.getCursorPosition();
      editor.gotoLine(next_pos.row + 1, next_pos.column - 3);
  }

  function insertItalicText() {
      var current_position = editor.getCursorPosition();
      console.log(current_position);
      session.insert(current_position, '__ ');

      // for moving cursor at center of bold mark
      var next_pos = editor.getCursorPosition();
      editor.gotoLine(next_pos.row + 1, next_pos.column - 2);
  }

  function insertUnderlineText() {
      var current_position = editor.getCursorPosition();
      console.log(current_position);
      session.insert(current_position, '<u></u> ');

      // for moving cursor at center of bold mark
      var next_pos = editor.getCursorPosition();
      editor.gotoLine(next_pos.row + 1, next_pos.column - 5);
  }
</script>

app/views/post/show.html.erb
<%= markdown(@post.content) %>

app/views/shared/_user_dropdown.html.erb
<div class="">
  <button data-dropdown-toggle="dropdown" class="text-black font-medium px-2 py-1.5 rounded-lg text-sm text-center inline-flex items-center" type="button">
    <%= user.username %>
    <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
  </button>
  <!-- Dropdown menu -->
  <div class="hidden bg-white text-base z-50 list-none divide-y divide-gray-100 rounded-xl shadow my-4" id="dropdown">
    <div class="px-4 py-3">
      <span class="block text-sm text-gray-400">Login as:</span>
      <span class="block text-sm font-medium text-gray-900 truncate"><%= user.email %></span>
    </div>
    <ul class="py-1" aria-labelledby="dropdown">
      <li>
        <a href="#" class="text-sm hover:bg-gray-100 text-gray-700 block px-4 py-2">Profile</a>
      </li>
      <li>
        <a href="#" class="text-sm hover:bg-gray-100 text-gray-700 block px-4 py-2">Settings</a>
      </li>
      <li>
        <%= link_to "Edit profile", edit_user_registration_path, class: 'text-sm hover:bg-gray-100 text-gray-700 block px-4 py-2' %>
      </li>
    </ul>
    <div class="">
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'rounded-b-xl w-full text-left text-sm hover:bg-gray-100 text-red-600 block px-4 py-2' %>
    </div>
  </div>
</div>